<?php

/**
 * @file
 * Contains dragomans_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dragomans_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dragomans module.
    case 'help.page.dragomans_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('dragomans_views') . '</p>';
      return $output;

    default:
  }
}


